blueprint:
  name: Time Of Day Motion-activated Light
  description: Turn on a light when motion is detected after the sun is set and the house is in Home mode.
  domain: automation
  source_url: https://raw.githubusercontent.com/EnvillePlease/Time-Of-Day-Motion-Lights/main/tod_motion_lights.yaml
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    sunset_offset:
      name: Offset to turn on lights
      description: Define offset to sunset
      default: -30
      selector:
        number:
          min: -60
          max: 120
          unit_of_measurement: minutes
    sunrise_offset:
      name: Offset to turn off lights
      description: Define offset to sunrise
      default: 30
      selector:
        number:
          min: -60
          max: 120
          unit_of_measurement: minutes

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

  condition:
  - condition: sun
    before: sunrise
    before_offset: !input sunrise_offset
    after: sunset
    after_offset: !input sunset_offset
  - condition: or
    conditions:
    - condition: state
      entity_id: input_select.house_mode
      state: Home
    - condition: state
      entity_id: input_select.house_mode
      state: Kids In Bed
    - condition: state
      entity_id: input_select.house_mode
      state: Working From Home

action:
  - service: light.turn_on
    data:
      brightness_pct: 100
    target:
      entity_id: !input light_target
  - wait_for_trigger:
    - platform: state
      entity_id: !input motion_entity
      from: 'on'
      to: 'off'
    timeout: !input no_motion_wait
  - service: light.turn_off
    data: {}
    target:
      entity_id: !input light_target
